Update crobex_const.yml

diff --git a/.github/workflows/crobex_const.yml b/.github/workflows/crobex_const.yml
--- a/.github/workflows/crobex_const.yml
+++ b/.github/workflows/crobex_const.yml
@@ -28,6 +28,12 @@ jobs:
         run: |
           git config --global user.name "github-actions"
           git config --global user.email "actions@github.com"
-          git add crobex_constituents_history.csv
-          git commit -m "Update Crobex constituents on $(date +'%Y-%m-%d')" || echo "No changes to commit"
+
+          if [ -f crobex_constituents_history.csv ]; then
+            git add crobex_constituents_history.csv
+            git commit -m "Update Crobex constituents on $(date +'%Y-%m-%d')" || echo "No changes to commit"
+            git push
+          else
+            echo "⚠️ File crobex_constituents_history.csv not found — skipping commit."
+          fi
           git push
